version: "3.9"

services:
  server:
    build: ./server
    container_name: music-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/src/.env
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    command: npm run dev   # or npm start

volumes:
  node_modules:
